# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/wan24-Crypto-BC.sln --ignore-failed-sources
    - name: Build lib
      run: dotnet build "./src/wan24-Crypto-BC/wan24-Crypto-BC.csproj" --no-restore
    - name: Build tests
      run: dotnet build "./src/wan24-Crypto-BC Tests/wan24-Crypto-BC Tests.csproj" --no-restore
    - name: Test
      run: dotnet test ./src/wan24-Crypto-BC.sln --no-build --verbosity normal
